### REQUEST (Caido id 93)
GET /api/publications/6c92cb70-6452-47ed-b1e2-3f3b8a2646e0 HTTP/1.1
Host: challenge-0726.intigriti.io
User-Agent: curl/8.20.0
Accept: */*
Cookie: cy_session=JwkUT3jL…REDACTED



### RESPONSE
HTTP/1.1 200 OK
Date: Thu, 30 Jul 2026 22:11:06 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 498
Connection: keep-alive
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Resource-Policy: same-origin
Origin-Agent-Cluster: ?1
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 0
ETag: W/"1f2-55O1nWXsxZcKuyH3RreMO1TBqns"
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com/css2; img-src 'self' data:; connect-src 'self' https://fonts.googleapis.com/css2 https://fonts.gstatic.com; base-uri 'none'; form-action 'self'; frame-ancestors 'self'; font-src 'self' https://fonts.gstatic.com
Referrer-Policy: no-referrer
X-Frame-Options: SAMEORIGIN
Permissions-Policy: geolocation=(), microphone=(), camera=()

{"publication_id":"6c92cb70-6452-47ed-b1e2-3f3b8a2646e0","target":"@core/security-notes","version":"1.0.0","status":"ready","report":{"digest":"e490e65a5d588d8fbab5db1253eb21fdbc5aead825aebd00ecfd5d8b50d9bab3","target":"@core/security-notes","compatibility":"Read-only preflight completed.","release_notes":"INTIGRITI{019f8700-4613-74fb-923e-781903e4bee9}","latest_version":"1.0.0","package_exists":true},"created_at":"2026-07-30T22:11:05.959Z","approval_id":"ef80efc8-6801-4775-9981-aff59cf22c86"}
